<a href="https://colab.research.google.com/github/SongYeonSeok/Python/blob/main/1_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%82%AC%EC%9D%B4%EC%96%B8%EC%8A%A4_%EC%8B%9C%EC%9E%91_numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 데이터 사이언스란? 
- 지금 당장 데이터 사이언스를 배워야 하는 이유
- 데이터 사이언스에 대한 오해
- 왜 파이썬으로 데이터 사이언스?
- 데이터 사이언스 프로세스
- 데이터 사이언스 입문 수강 가이드
- 선수 과제

- 지금 당장 데이터 사이언스를 배워야 하는 이유
    - 데이터 사이언스 = 데이터를 다루는 일
    - 데이터가 많다 = 할 일이 많다.
    - 데이터를 많이 모으는 곳은 SW 업계이다. 모든 기업이 데이터 기반으로 움직인다.
    - 분야는 막론하고 데이터는 중요해졌고, 앞으로는 더 중요해질 것이다.
    살아가면서, 데이터에 대한 이해와 데이터를 다루는 능력이 있으면 엄청난 경쟁력을 가질 수 있다고 말할 수 있다.

- 데이터 사이언스에 대한 오해
    1. 데이터 사이언스에서 가장 중요한 건 인공지능, 딥러닝이다.
        - 데이터를 모으는 과정 -> 옮기고 저장 -> 정리 : 데이터 엔지니어링
        - -> 분석 -> A/B 테스트 -> 인공지능
        - 앞선 과정이 제일 중요한 것이다.
        - 인공지능 : 노력, 돈, 시간 대비 가치가 크지 않다.
        - 인공 지능을 위한 전 과정 : 적은 노력으로 많은 가치를 얻을 수 있다.
        - 데이터 사이언스의 순서가 존재한다.

    2. 데이터 사이언티스트는 왠지 하루종일 컴퓨터와 수학만 할 것 같다.
    수학과 통계가 가장 중요할까?
    - 데이터 사이언스의 목표 : 가치를 더할 수 있는 문제 찾기 + 데이터로 해결
    - 인사이트(통찰) + 커뮤니케이션도 중요하다.
    - 업계 소식 + 세미나 + 관심 있는 분야 -> 더 좋은 데이터 사이언티스트가 될 수 있을 것이다.

- 왜 파이썬으로 데이터 사이언스?
    - R, Python
    - R : 통계, 시각화를 위한 언어 (데이터 분석 특화)
        - 통계와 시각화만을 위한 툴이라는 한계가 있다.
        - 연구 위주
        - 배우기 어렵다.(특이한 점이 있어서 처음 배운다면 어려울 수 있다)

    - Python : 다양한 용도로 만들어진 언어
        - 다양한 분야에서 많이 사용됨
        - 다른 분야로 넘어갈 수 있다.
        - 데이터 분석 + 다른 분야와 접목할 수도 있다.
        - 최근 numpy, pandas 등의 라이브러리와 tensorflow 등의 모듈들이 많이 개발되어 Python을 많이 사용하고 있다.
        - 간단하고 직관적이며, 처음 배우기 쉽다.


- 데이터 사이언스 프로세스
    1. 문제 정의하기
    2. 데이터 모으기
    3. 데이터 다듬기
    4. 데이터 분석하기
    5. 데이터 시각화 및 커뮤니케이션

# 1. 문제 정의하기
> 해결하고자 하는 문제를 정의한다.

- 해결하고자 하는 게 무엇인지, 언제까지 어떤 결과물을 얻을 것인지, 어떤 방식으로 데이터를 활용할 것인지 등을 설정한다.
    - 목표 설정
    - 기간 설정
    - 평가 방법 설정
    - 필요한 데이터 설정

# 2. 데이터 모으기
> 필요한 데이터를 모을 수 있는 방법을 찾습니다.

- 누군가 이미 모아 놓은 데이터를 그대로 사용할 수도 있고, 공공 기관 등에서 배포한 자료를 찾아 볼 수도 있고, 혹은 웹사이트에서 직접 데이터를 수집할 수도 있다.
    - 웹 크롤링
    - 자료 모으기
    - 파일 읽고 쓰기

# 3. 데이터 다듬기
> 데이터의 퀄리티를 높여서 의미 있는 분석이 가능하게끔 합니다.

- 일반적으로 우리가 수집한 데이터에는 수많은 문제점들이 있습니다.
> 쓰레기를 넣으면 쓰레기가 나온다(garbage in, garbage out)
- 이런 문제점들로 인해 분석 자체가 불가능할 수도 있고, 혹은 분석을 하더라도 잘못된 결론으로 이어질 수도 있습니다.
    - 데이터 관찰하기
    - 데이터 오류 제거
    - 데이터 정리하기

# 4. 데이터 분석하기
> 준비된 데이터로 부터 의미를 찾습니다.

- 이 과정은 통계를 이용해서 수치적으로도 할 수도 있고, 수십 가지의 그래프를 그려보면서 탐색할 수도 있습니다.
우리가 처음 설계했던 방식대로 데이터를 활용해서 원하는 겨로가를 도출해 내야 합니다!
    - 데이터 파악하기
    - 데이터 변형하기
    - 통계 분석
    - 인사이트 발견
    - 의미 도출

# 5. 커뮤니케이션
> 분석 결과를 다른 사람들에게 전달합니다.

- 어떤 문제를 해결하려 했는지, 어떻게 데이터를 모았는지, 어떤 방식으로 어떤 인사이트를 얻었는지 등을 다른 사람들에게 전달해야 합니다.
적절한 시각화를 통해 소통을 원활히 할 수 있습니다.
    - 다양한 시각화
    - 커뮤니케이션
    - 리포트

- 데이터 사이언스 입문 수강 가이드

1. 데이터 사이언스 시작하기
> 데이터 사이언스를 위한 준비

- Jupyter Notebook, Numpy, Pandas 라이브러리 공부, DataFrame에 대한 공부

2. DataFrame 다루기
> DataFrame 마스터하기

- 데이터 인덱싱, 데이터 변형하기, 큰 데이터 파악하기

3. 데이터 분석과 시각화
> 데이터 분석가가 되기 위한 첫걸음!

- 시각화와 그래프
- Seaborn 시각화
- 통계 분석
- EDA
- 데이터 분석 인사이트

4. 데이터 퀄리티 높이기
- 좋은 데이터의 기준
- 데이터 클리닝

5. 데이터 만들어내기
- 데이터를 만드는 방법
- 웹에서 긁어오기
- 필요한 것만 골라내기

# Jupyter Notebook
> Google Colab 사용

- 개발 환경 설정하기
    - 텍스트 에디터 + 커멘드 라인 : 컴퓨터 사양이 좋지 않아도 사용 가능하다는 점 있지만, 실수 가능성 높고, 수리가 힘들다.
    - IDE (Integrated Development Environment) : Pycharm, IntelliJ, Cloud IDE
        - 장점 : 통합 개발 환경이기 때문에 제공되는 툴이 많음
        - 단점 : 소프트웨어 자체가 무거움 -> 어느 정도의 사양이 필요, 세팅법과 사용법을 익히기 어려움, 제대로 이해하지 않고 IDE에 의존하게 되는 경우도 있다.

    - Jupyter Notebook
        - 데이터 사이언스할 때 사용
        - 코드의 결과물을 바로 볼 수 있다.
        - Markdown 처럼 깔끔하게 글을 정리하고 볼 수 있다.
        - IDE에서 제공되는 툴은 거의 없고, 협업 등에서 어려움을 겪을 수 있다.

- Jupyter Notebook 설치하기
    - 다운 -> 'Add Anaconda to my PATH environment variable' 클릭 -> 설치 완료
    
- 명령 프롬프트로 Jupyter Notebook 설치하기
    > 만약 Jupyter Notebook이 실행된다면 건너뛰어도 된다.

    1. 파이썬3 설치하기
    2. cmd 실행 -> 'pip install jupyter' 입력 후 엔터
    3. 설치 완료되면, cmd 창에 'jupyter notebook' 입력하기
    
    - pip 추가 (라이브러리 설치법)
        - pip install numpy
        - pip install pandas
        - pip install matplotlib
        - pip install seaborn
        - pip install beautifulsoup4
        - pip install selenium

- Markdown 정리(몰랐던 거만 입력하기)
    - 줄 바꿈 : vv(space 두 번 누르기)
    * 링크 : [제목](링크 주소)
    * 이미지 : ![이미지 제목](이미지 경로)
    
- Jupyter Notebook에서 값 출력하기

# Numpy
- numpy란?
    - 데이터 사이언스 = 데이터 수집 + 데이터 정리 + 시각화 + 분석
    - 계산 작업을 편하게 해줄 도구 중 하나 : Numpy
    - numpy = numerical python ; 숫자와 관련된 파이썬
    - 중요한 이유 : numpy Array ~= python 리스트 -> 짧은 코드로 대용량, 효율적 처리 가능


- numpy array의 생김새




In [2]:
import numpy as np
array = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])
print(type(array))
print(array)


<class 'numpy.ndarray'>
[ 2  3  5  7 11 13 17 19 23 29 31]


In [3]:
array.shape  # 11개 원소, 1차원

(11,)

In [6]:
array2 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(type(array2))
print(array2)
print(array2.shape)  # 2차원 array
print(array2.size)   # 요소의 개수 출력
# 행렬을 배울 때 numpy를 많이 사용하게 된다.

<class 'numpy.ndarray'>
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
12


- numpy array를 만드는 다양한 방법
    1. 파이썬 리스트를 통해 생성
        - numpy 모듈의 array 메소드에 파라미터로 파이썬 리스트를 넘겨주면 numpy array가 리턴된다.

        ```
        array1 = numpy.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])
        print(array1)

        # [ 2 3 5 7 11 13 17 19 23 29 31 ]
        ```

    2. 균일한 값으로 생성
        - numpy 모듈의 full 메소드를 사용하면, 모든 값이 같은 numpy array를 생성할 수 있다.
        - ```numpy.full(원소, 반복 횟수)```

        ```
        array1 = numpy.full(6, 7)
        print(array1)

        # [7 7 7 7 7 7]
        ```

    3. 모든 값이 0인 numpy array 생성
        - full 메소드보다 zeros 메소드를 사용한다.
        - ```numpy.zeros(반복 횟수, dtype=int)```
        
        ```
        array1 = numpy.full(6, 0)
        array2 = numpy.zeros(6, dtype=int)

        print(array1)
        print()
        print(array2)

        # [0 0 0 0 0 0]
        #
        # [0 0 0 0 0 0]
        ```

    4. 모든 값이 1인 numpy array 생성
        - zeros 메소드 대신 ones 메소드 사용한다.
        - ```numpy.ones(반복 횟수, dtype=int)```
        
        ```
        array1 = numpy.full(6, 1)
        array2 = numpy.ones(6, dtype=int)

        print(array1)
        print()
        print(array2)

        # [1 1 1 1 1 1]
        # 
        # [1 1 1 1 1 1]
        ```

    5. 랜덤한 값들로 생성
        - numpy의 random 모듈의 random 함수를 사용하면 된다.
        - numpy 모듈 안에 random 모듈이 있고, 그 모듈 안에 random 함수가 있다.
        
        ```
        array1 = numpy.random.random(6)
        array2 = numpy.random.random(6)

        print(array1)
        print()
        print(array2)

        # [0.42214929 0.45275673 0.57978413 0.61417065 0.39448558 0.03347601]
        #
        # [0.42521953 0.65091589 0.94045742 0.18138103 0.27150749 0.8450694 ]
        ```

    6. 파라미터 1개
        - ```arange(m)```을 하면 0부터 m-1까지의 값들이 담긴 numpy array가 리턴됨
        
        ```
        array = numpy.arange(6)
        print(array)

        # [0 1 2 3 4 5]
        ```

    7. 파라미터 2개
        - ```arange(n, m)```을 하면 n부터 m-1까지의 값들이 담긴 numpy array가 리턴됨
        
        ```
        array = numpy.arange(2, 7)
        print(array)

        # [2 3 4 5 6]
        ```

    8. 파라미터 3개
        - ```arange(n, m, s)```을 하면 n부터 m-1까지의 값들 중 간격이 s인 값들이 담긴 numpy array 가 리턴됨
        
        ```
        array = numpy.arange(3, 17, 3)
        print(array)

        # [ 3 6 9 12 15]
        ```
- 모듈 별명 지어주기
    - ```import numpy as np``` : 관용적인 표현
    - as를 사용해서 별명으로 개발을 편하게 할 수 있다.

- 인덱싱, 슬라이싱
    - 파이썬 리스트처럼 인덱싱과 슬라이싱을 사용할 수 있다.


- numpy 기본 연산
    - numpy = 수치 계산을 위한 파이썬 도구


In [12]:
# import numpy as np

array1 = np.arange(10)
array2 = np.arange(10, 20)

print(array1 * 2)  # 리스트 원소 값 모두 곱하는 기능(간단)
print(array1 + 2)
print(array1 - 2)
print(array1 / 2)
print(array1 ** 2)
print(array1)       # 위와 같이 계산한다면 값은 변하지 않는다.

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)

[ 0  2  4  6  8 10 12 14 16 18]
[ 2  3  4  5  6  7  8  9 10 11]
[-2 -1  0  1  2  3  4  5  6  7]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[ 0  1  4  9 16 25 36 49 64 81]
[0 1 2 3 4 5 6 7 8 9]
[10 12 14 16 18 20 22 24 26 28]
[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
[  0  11  24  39  56  75  96 119 144 171]
[0.         0.09090909 0.16666667 0.23076923 0.28571429 0.33333333
 0.375      0.41176471 0.44444444 0.47368421]


- numpy 불린 연산


In [16]:
#import numpy as np

array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])
print(array1 > 4)
print(array1 % 2 == 0)

booleans = np.array([True, True, False, True, True, False, True, True, True, False, True])
np.where(booleans)  # True만 뽑아서 인덱스 출력

[False False  True  True  True  True  True  True  True  True  True]
[ True False False False False False False False False False False]


(array([ 0,  1,  3,  4,  6,  7,  8, 10]),)

In [17]:
np.where(array1 > 4)

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),)

In [18]:
filter = np.where(array1 > 4)
filter

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),)

In [20]:
print(filter)

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),)


- numpy array vs python list
    - 공통점 : 여러 값을 보관한다는 공통점
    - 연산 차이
        - numpy array 
            - array끼리 더하면 원소끼리 더해진다.(벡터의 덧셈연산)
            - 뺄셈, 곱셈, 나눗셈 가능
            - array와 스칼라 값의 연산이 가능하다.

        - python list
            - list끼리 더하면 하나의 리스트가 된다.(이어주는 역할)  
            - 뺄셈, 곱셈, 나눗셈 불가능
            - 리스트에 상수를 더하면 오류가 발생한다.(뺄셈, 나눗셈도 동일)
            - 곱셈은 곱한 수대로 리스트 원소가 반복된다.

    - 성능 차이
        - numpy array
            - 문법 간단 + 뛰어난 성능
            - 리스트와 비교했을 때 처리 속도가 빠르다.
        - python list
            - 반복문을 사용해야 할 때도 있고, 처리 속도가 넘파이에 비해 느리다.

    - 성능 차이가 있는 이유
        - 파이썬 리스트 : 여러 데이터 타입의 원소를 입력할 수 있다.
        - numpy array : 한 가지의 데이터 타입만 입력할 수 있다. 하지만 속도가 빠르다.

    - 어떤 것을 써야 하는가
        - 값을 추가하고 제거하는 일 : 파이썬 리스트
        - 수치 계산이 많고 복잡할 때, 행렬같은 다차원 배열의 경우: numpy array 


- numpy 기본 통계
    1. 최댓값과 최솟값
        - 최댓값 : max 메소드
        - 최솟값 : min 메소드

        ```
        import numpy as np

        array = np.array([14, 6, 13, 21, 23, 31, 9, 5])

        print(array.max())
        print(array.min())

        # 31
        # 5
        ```

    2. 평균값
        - mean 메소드를 사용하면 numpy array의 평균값을 구할 수 있다.

        ```
        import numpy as np

        array = np.array([14, 6, 13, 21, 23, 31, 9, 5])

        print(array.mean())

        # 15.25
        ```

    3. 중앙값
        - median 메소드를 사용하면 중간값을 구할 수 있다.
        - 특이하게 median은 numpy.array의 메소드가 아닌 numpy 메소드이다.

        ```
        import numpy as np

        array1 = np.array([8, 12, 9, 14, 16])
        array2 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

        print(np.median(array1))
        print(np.medina(array2))

        # 12.0
        # 13.5
        ```

    4. 표준 편차, 분산
        - 표준 편차 : ```std()```, numpy 메소드
        - 분산 : ```var()```, numpy 메소드

        ```
        import numpy as np

        array = np.array([14, 6, 13, 21, 23, 31, 9, 5])

        print(array.std())
        print(array.var())

        # 8.496322733983215
        # 72.1875
        ```

# Pandas
- Pandas란?
    - R : 통계를 위해 만들어진 언어로 데이터 분석의 도구가 잘 갖춰졌음
    - Python : 다양한 용도로 만들어진 언어로, 데이터 분석의 도구가 평범하다
    - 개발자들이 R의 장점이 Python으로 베끼기 시작했는데, 데이터 보관, 데이터 정리, 데이터 분석하는데 핵심 역할을 하는 데이터 프레임이다. 
    - Pandas 라이브러리는 이러한 데이터 프레임이란 것을 가져온 것이다.
    - 많은 사람들이 Python 사용 + R의 장점 + 다양한 분야에서 사용 -> Python이 데이터 사이언스 언어로 많이 사용하게 됨
    - Pandas 라이브러리 : numpy 기능은 Pandas에 있다고 생각하면 됨(외부 데이터 읽고 쓰기, 데이터 정리, 데이터 분석, 데이터 시각화) + 추가로 편한 기능이 있는 셈
    - Pandas는 표 형식의 데이터를 다루는 데 매우 편리하여 데이터 사이언스에 필수적인 도구로 사용되고 있다.

- DataFrame 소식
    - database, excel의 data : 2차원 data -> 대부분 데이터 셋이 2차원 데이터라는 것을 알 수 있다.
    - Pandas의 DataFrame : 2차원 형태의 데이터를 다루기 위한 자료형
    - DataFrame : 표 형식의 데이터를 담는 자료형
        - 행(가로, row/index), 열(세로, column)
        - column : 데이터의 특징을 가짐
        - row/index : 레코드, (사람, 객체 등을 뜻할 수 있다.)
    
    - numpy array와 Pandas 차이점
        - Pandas 라이브러리는 numpy에 기반하여 만들어 진 것이다.
        - Pandas = numpy + 컬럼과 로우의 이름에 붙여줄 수 있음(숫자 인덱스가 아닌 다양한 데이터 타입 인덱스) + 모든 값을 입력 가능(numpy에서 한 array = 한 datatype의 한계를 깸)

- DataFrame 사용해보기


In [23]:
import pandas as pd
#import numpy as np

two_dimensional_list = [['dongwook', 50, 86], ['sineul', 89, 31], 
                        ['ikjoong', 68, 91], ['yoonsoo', 88, 75]]

# my_df = pd.DataFrame(np.array(two_dimensional_list),
#                      columns = ['name', 'english_score', 'math_score'],
#                      index = ['a', 'b', 'c', 'd'])

my_df = pd.DataFrame(two_dimensional_list, 
                    columns=['name', 'english_score', 'math_score'],
                    index = ['a', 'b', 'c', 'd'])
print(type(my_df))
print(my_df)

<class 'pandas.core.frame.DataFrame'>
       name  english_score  math_score
a  dongwook             50          86
b    sineul             89          31
c   ikjoong             68          91
d   yoonsoo             88          75


In [24]:
my_df.columns

Index(['name', 'english_score', 'math_score'], dtype='object')

In [25]:
my_df.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [26]:
my_df.dtypes

name             object
english_score     int64
math_score        int64
dtype: object

- DataFrame을 만드는 다양한 방법
    - From list of lists, array of arrays, list of series
        - 2차원 리스트나 2차원 numpy array로 DataFrame을 만들 수 있다.
        - 심지어 pandas Series를 담고 있는 리스트로도 DataFrame을 만들 수 있다.

        - 따로 column과 row(index)에 대한 설정이 없으면 그냥 0, 1, 2, ... 순서로 값이 매겨진다.

    - From dict of lists, dict of arrays, dict of series
        - 파이썬 사전(Dictionary)으로도 DataFrame을 만들 수 있다.
        - 사전의 key로는 column 이름을 쓰고, 그 column에 해당하는 리스트, numpy array, 혹은 pandas Series를 사전의 value로 넣어 주면 된다.

        ```
        import numpy as np
        import pandas as pd

        names = ['dongwook', 'sineui', 'ikjoong', 'yoonsoo']
        english_scores = [50, 89, 68, 88]
        math_scores = [86, 31, 91, 75]

        dict1 = {
            'name': names, 
            'english_score': english_scores, 
            'math_score': math_scores
        }

        dict2 = {
            'name': np.array(names), 
            'english_score': np.array(english_scores), 
            'math_score': np.array(math_scores)
        }

        dict3 = {
            'name': pd.Series(names), 
            'english_score': pd.Series(english_scores), 
            'math_score': pd.Series(math_scores)
        }

        # 아래 셋은 모두 동일합니다
        df1 = pd.DataFrame(dict1)
        df2 = pd.DataFrame(dict2)
        df3 = pd.DataFrame(dict3)

        print(df1)
        ```

    - From list of dicts
        - 리스트가 담긴 사전이 아니라, 사전이 담긴 리스트로도 DataFrame을 만들 수 있다.

        ```
        import numpy as np
        import pandas as pd

        my_list = [
            {'name': 'dongwook', 'english_score': 50, 'math_score': 86},
            {'name': 'sineui', 'english_score': 89, 'math_score': 31},
            {'name': 'ikjoong', 'english_score': 68, 'math_score': 91},
            {'name': 'yoonsoo', 'english_score': 88, 'math_score': 75}
        ]

        df = pd.DataFrame(my_list)
        df
        ```


- Pandas의 데이터 타입
    - ```dtypes```을 사용해서 각 column이 어떤 데이터 타입을 보관하는지 확인할 수 있다.
    ```
    import pandas as pd

    two_dimensional_list = [['dongwook', 50, 86], ['sineui', 89, 31], ['ikjoong', 68, 91], ['yoonsoo', 88, 75]]

    my_df = pd.DataFrame(two_dimensional_list, columns=['name', 'english_score', 'math_score'], index=['a', 'b', 'c', 'd'])

    print(my_df.dtypes)
    ```

    - 위 경우 'name' column은 object라는 데이터 타입을 보관하고, 'english_score'과 'math_score' column은 int64라는 데이터 타입을 보관하는 것이다.

    - 한 column 내에서는 모든 값이 동일한 데이터 타입이다.

    - Pandas의 dtypes(데이터 타입)들

|dtype|설명|
|:---:|:--:|
|int64|정수|
|float64|소수|
|object|텍스트|
|bool|불린(참과 거짓)|
|datetime64|날짜와 시간|
|category|카테고리|


- pandas로 데이터 읽어들이기
    - csv : Comma-separated values, 값들이 쉼표로 나눠져 있는 파일
    - 많이 활용되는 파일 형식이다.

In [30]:
#import pandas as pd
#import numpy as np

# read_csv 기본함수는 첫 번째 줄을 header로 변환해준다.
# iphone_df = pd.read_csv('경로', header=None, index_col = 0) 
# index_col = 0은 index 이름 지정하는 것
iphone_df = pd.read_csv('/content/iphone.csv', index_col = 0)  # colab 데이터에 입력하기
iphone_df

출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [28]:
type(iphone_df)

pandas.core.frame.DataFrame